
import React from 'react';
import { FoxIcon } from './Icons';

export const Header: React.FC = () => {
    return (
        <header className="text-center space-y-4 animate-fade-in-up">
            <div className="inline-flex items-center justify-center bg-brand-orange/20 text-brand-orange p-4 rounded-full">
               <FoxIcon className="h-10 w-10" />
            </div>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold font-display text-brand-brown tracking-tight">
                The Mooing Fox Salon
            </h1>
            <p className="max-w-2xl mx-auto text-lg text-brand-brown/80">
                A complete branding & marketing concept, generated by AI. Whimsical, weird, and ready for the world.
            </p>
        </header>
    );
};
